const SET_USER = 'SET_USER';
const ALTER_USER = 'ALTER_USER';
const ALTER_JUST_USER = 'ALTER_JUST_USER';
const SET_TOKEN = 'SET_TOKEN';
const SET_BOTTOM_TAB_BAR = 'SET_BOTTOM_TAB_BAR';
const SET_BOTTOM_TAB_BAR_INDEX = 'SET_BOTTOM_TAB_BAR_INDEX';
const SET_LANGUAGE = 'SET_LANGUAGE';

export {
  SET_USER,
  ALTER_USER,
  ALTER_JUST_USER,
  SET_TOKEN,
  SET_BOTTOM_TAB_BAR,
  SET_BOTTOM_TAB_BAR_INDEX,
  SET_LANGUAGE,
};
